#!/bin/sh -eu
if [ -z "${EXPRESS_BACKEND_SERVICE_SERVICE_HOST:-}" ]; then
    EXPRESS_BACKEND_SERVICE_SERVICE_HOST=localhost
fi
if [ -z "${EXPRESS_BACKEND_SERVICE_SERVICE_PORT:-}" ]; then
    EXPRESS_BACKEND_SERVICE_SERVICE_PORT=80
fi

cat <<EOF
window.API_ROOT="http://${EXPRESS_BACKEND_SERVICE_SERVICE_HOST}:${EXPRESS_BACKEND_SERVICE_SERVICE_PORT}/api";
EOF

# if [ -z "${IS_LOCAL_OR_MINIKUBE:-}" ]; then
#     IS_LOCAL_OR_MINIKUBE=false
# fi